### PR TITLE
refactor: use type imports and recommended lint rules, bump dependencies

### PR DESCRIPTION
**Pull request by sjwilczynski**
In scope of this PR we make set of our eslint/tsconfig rules a little stricter:
* we add recommended config from `@typescript-eslint` and fix major issues
* we force using type import where applicable ([importsNotUsedAsValues](https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues)) - that is useful particularly for modern build tools (when [isolatedModules](https://www.typescriptlang.org/tsconfig#isolatedModules) is also set)  and from dev perspective allows to easier understand what is just needed for type and what during runtime
* some more reasonable defaults in tsconfig ([forceConsistentCasingInFileNames](https://www.typescriptlang.org/tsconfig#forceConsistentCasingInFileNames), [noUnusedLocals](https://www.typescriptlang.org/tsconfig#noUnusedLocals), [noUnusedParameters](https://www.typescriptlang.org/tsconfig#noUnusedParameters))
* bump eslint and typescript related dependencies

### CODE REVIEW

**Comment by freiksenet** [comment]
We don't depend on Typescript here, right? (if we do we need to upgrade it). Looks good otherwise.

**Comment by sjwilczynski** [comment]
@freiksenet I bumped TS but needed to bump apollo client and adjust pipeline to use node 16. Let me know if that is ok :)

**Comment by freiksenet** [comment]
if you are bumping versions, change type can't be none - we need major I think.

**Comment by sjwilczynski** [comment]
> if you are bumping versions, change type can't be none - we need major I think.

Good callout, I adjusted the change file for `nova-react-test-utils`, kept the rest as none, as in those packages there were no bumps

**Pull request merged**
